package c80_test

import (
	"github.com/reiver/go-c80"
)

func ExampleDye() {

	c80.Dye(3)
	c80.Show()

	// Output:
	// IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaPxwLAAAATElEQVR4nOzMQQ0AAAgEICO52b+bIe53gwDMZVYgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCQXvwAQAA///AzoGLUCkA2wAAAABJRU5ErkJggg==
}
