package c80_test

import (
	"github.com/reiver/go-c80"

	"strings"

	"testing"
)

func TestShowTo(t *testing.T) {

	tests := []struct{
		Index uint8
		Expected string
	}{
		{
			Index:0,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAAJ0lEQVR4nOzAgQAAAADCsPypMzjBNgAAAAAAAAAAAAAAgPYAAAD//zB/AAGXmfMxAAAAAElFTkSuQmCC",
		},
		{
			Index:1,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAAS0lEQVR4nOzMQREAAAgDICNo/7KG2G8HAZjLrEAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCASC9uADAAD//wtJKy/PQX3gAAAAAElFTkSuQmCC",
		},
		{
			Index:2,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAAS0lEQVR4nOzMQREAAAgDIKN49g9piP12EIC5zAoEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgaA8+AAD//+YEVl1ylMqvAAAAAElFTkSuQmCC",
		},
		{
			Index:3,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMQQ0AAAgEICO52b+bIe53gwDMZVYgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCQXvwAQAA///AzoGLUCkA2wAAAABJRU5ErkJggg==",
		},
		{
			Index:4,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMMREAAAgEIKM52D+TIX77gwDMZVYgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCQXvwAQAA//+bmKy5ApEl1AAAAABJRU5ErkJggg==",
		},
		{
			Index:5,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMMREAAAgEICO62L+KIX77gwDMZVYgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCQXvwAQAA//92YtfnUZGBjQAAAABJRU5ErkJggg==",
		},
		{
			Index:6,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMMREAAAgEIKM62T+CIX77gwDMZVYgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCQXvwAQAA//9RLAMkqFevTAAAAABJRU5ErkJggg==",
		},
		{
			Index:7,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAAS0lEQVR4nOzMMREAAAgEICO7Wd8Qv/1BAOYyKxAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoGgPfgAAAD//yv2LlJxZU1IAAAAAElFTkSuQmCC",
		},

		{
			Index:8,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAAS0lEQVR4nOzMMREAAAgEIKM7GtsQv/1BAOYyKxAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoGgPfgAAAD//wbAWYDRIj+FAAAAAElFTkSuQmCC",
		},
		{
			Index:9,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAAS0lEQVR4nOzMIREAAAgEMPorLG0J8e5vC7C5zAoEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgaA8+AAD//+F7hK7CCd10AAAAAElFTkSuQmCC",
		},
		{
			Index:10,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMMREAAAgEIPuncDalIX77gwDMZVYgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCQXvwAQAA//+8Ra/cugNRVwAAAABJRU5ErkJggg==",
		},
		{
			Index:11,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMMREAAAgEIPuncbecIX77gwDMZVYgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCQXvwAQAA//+XD9sKjC1kZgAAAABJRU5ErkJggg==",
		},
		{
			Index:12,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMQREAAAgDIPunMoChDLHfDgIwl1mBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBO3BBwAA//9x2QZHMo9Y7gAAAABJRU5ErkJggg==",
		},
		{
			Index:13,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMQREAAAgDIPuns4BdDLHfDgIwl1mBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBO3BBwAA//9MozF1Z0uVqgAAAABJRU5ErkJggg==",
		},
		{
			Index:14,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAATElEQVR4nOzMQREAAAgDIPunNIEZDLHfDgIwl1mBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBO3BBwAA//8nbVyjr1UtWgAAAABJRU5ErkJggg==",
		},
		{
			Index:15,
			Expected:"IMAGE:iVBORw0KGgoAAAANSUhEUgAAAH8AAAC/BAMAAAAlex6UAAAAMFBMVEUBAQHeOCs5tUr/xwYAb7h2JnEstenMzMyAgID/AAAA/wD//wAAAP//AP8A//////9ssw/GAAAAS0lEQVR4nOzMQREAAAgDIPuntYGG2G8HAZjLrEAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCASC9uADAAD//wI3h9FPIDZzAAAAAElFTkSuQmCC",
		},
	}

	for testNumber, test := range tests {

		c80.Dye(test.Index)

		var buffer strings.Builder

		c80.ShowTo(&buffer)

		if expected, actual := test.Expected, buffer.String(); expected != actual {
			t.Errorf("For test #%d, what was actually gotten was not what was expected.", testNumber)
			t.Logf("EXPECTED: %q", expected)
			t.Logf("ACTUAL:   %q", actual)
			continue
		}
	}
}
